# Generated by Django 2.1.15 on 2020-01-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provided_RssLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=400, unique=True)),
                ('Insert_Date', models.DateTimeField(auto_now_add=True)),
                ('Process_N_Y', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RssData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=400)),
                ('Link', models.CharField(max_length=400)),
                ('Publish_date', models.CharField(max_length=400)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rssfeedclassified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=400)),
                ('Link', models.CharField(max_length=400)),
                ('Publish_date', models.CharField(max_length=400)),
                ('Description', models.TextField()),
                ('classification', models.CharField(max_length=400)),
                ('insertDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
