# Generated by Django 2.0 on 2020-01-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rssapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rss_table',
            name='Link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rss_table',
            name='Publish_date',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='rss_table',
            name='Title',
            field=models.CharField(max_length=255),
        ),
    ]
