# Generated by Django 2.0 on 2020-01-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rss_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Link', models.CharField(max_length=30)),
                ('Publish_date', models.CharField(max_length=50)),
                ('Description', models.TextField()),
            ],
        ),
    ]
